(function(){
  function safeImg(img, fallback){if(!img)return; img.addEventListener('error',()=>{img.style.display='none';if(fallback)fallback.style.display='grid'});img.addEventListener('load',()=>{if(fallback)fallback.style.display='none'});}
  function header(){const c=CR.getContent(); const el=document.querySelector('[data-announcement]');if(el)el.textContent=c.announcement;document.querySelectorAll('[data-brand]').forEach(e=>e.textContent=c.brand);updateCartCount();}
  function updateCartCount(){const n=CR.getCart().reduce((s,i)=>s+Number(i.qty||1),0);document.querySelectorAll('[data-cart-count]').forEach(e=>e.textContent=n)}
  function card(p){const price=CR.productPrice(p), hasSale=price<Number(p.price);return `<a class="product-card" href="produkt.html?id=${encodeURIComponent(p.id)}"><div class="product-img"><div class="img-fallback">CR</div><img src="${CR.escape(CR.imageSrc(p))}" alt="${CR.escape(p.name)}" onerror="this.style.display='none'"><span class="badge" style="${p.badge?'':'display:none'}">${CR.escape(p.badge||'')}</span></div><div class="product-info"><div class="product-kicker">${CR.escape(p.category)}</div><div class="product-name">${CR.escape(p.name)}</div><div class="price-row"><span class="price">${CR.money(price)}</span>${hasSale?`<span class="old">${CR.money(p.price)}</span><span class="sale">−${Number(p.discount)}%</span>`:(p.compareAt>p.price?`<span class="old">${CR.money(p.compareAt)}</span>`:'')}</div></div></a>`}
  function renderGrid(selector, products){const el=document.querySelector(selector);if(!el)return;el.innerHTML=products.filter(p=>p.active!==false).map(card).join('');}
  window.Shop={header,updateCartCount,card,renderGrid,safeImg,toast(msg){const t=document.querySelector('.toast');if(!t)return;t.textContent=msg;t.style.display='block';clearTimeout(t._x);t._x=setTimeout(()=>t.style.display='none',2200)}};
  document.addEventListener('DOMContentLoaded',header);
})();
